name: Test Windows
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'LICENSE'
  pull_request:
env:
  GO_VERSION: "1.19"
  TINYGO_VERSION: "0.25.0"
jobs:
  test:
    name: Test - Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install TinyGo - Windows
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop install tinygo@${{ env.TINYGO_VERSION }}

      - name: Run unit tests
        run: |
          go test -v -short -coverprofile="coverage.txt" -covermode=atomic .\...

#  module-test:
#    name: Module Integration Test - Windows
#    runs-on: windows-latest
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ env.GO_VERSION }}
#        id: go
#
#      - name: Install TinyGo - Windows
#        run: |
#          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
#          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
#          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
#          scoop install tinygo@${{ env.TINYGO_VERSION }}
#
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Run module integration tests
#        run: |
#          go test -v -tags=module_integration .\integration\...


