name: Test macOS
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'LICENSE'
  pull_request:
env:
  GO_VERSION: "1.19"
  TINYGO_VERSION: "0.25.0"
jobs:
  test:
    name: Test - macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install TinyGo - macOS
        run: |
          brew tap tinygo-org/tools
          brew install tinygo

      - name: Run unit tests
        run: make test

  integration:
    name: Integration Test - macOS
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Install TinyGo - macOS
        run: |
          brew tap tinygo-org/tools
          brew install tinygo

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        run: |
          set -x         
          docker version
          docker run --rm hello-world

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run integration tests
        run: make test-integration